# Generated by Django 6.0.5 on 2026-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_remove_invoice_prev_balance_invoice_current_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='current_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
