# Generated by Django 6.0.5 on 2026-05-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_remove_invoice_closing_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='previous_balance',
        ),
        migrations.AddField(
            model_name='invoice',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
